const FETCH_USER_SUCCESS = "user/FETCH_USER_SUCCESS";
const FETCH_USER_ERROR = "user/FETCH_USER_ERROR";
const LOGIN_SUCCESS = "user/LOGIN_SUCCESS";
const LOGIN_FAILURE = "user/LOGIN_FAILURE";
const LOGOUT_SUCCESS = "user/LOGOUT_SUCCESS";
const LOGOUT_FAILURE = "user/LOGOUT_FAILURE";

export default {
    FETCH_USER_SUCCESS,
    FETCH_USER_ERROR,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT_SUCCESS,
    LOGOUT_FAILURE
};