const FETCH_NUMBER_PROPERTIES_SUCCESS = "numberProperties/FETCH_NUMBER_PROPERTIES_SUCCESS";
const FETCH_NUMBER_PROPERTIES_ERROR = "numberProperties/FETCH_NUMBER_PROPERTIES_ERROR";
const FETCH_NUMBER_PROPERTIES_IS_LOADING = "numberProperties/FETCH_NUMBER_PROPERTIES_IS_LOADING";
const SET_SAMPLE_SIZE = "numberProperties/SET_SAMPLE_SIZE";

export default {
    FETCH_NUMBER_PROPERTIES_SUCCESS,
    FETCH_NUMBER_PROPERTIES_ERROR,
    FETCH_NUMBER_PROPERTIES_IS_LOADING,
    SET_SAMPLE_SIZE
};