const FETCH_DRAWINGS_SUCCESS = "drawings/FETCH_DRAWINGS_SUCCESS";
const FETCH_DRAWINGS_ERROR = "drawings/FETCH_DRAWINGS_ERROR";
const FETCH_DRAWINGS_IS_LOADING = "drawings/FETCH_DRAWINGS_IS_LOADING";
const SET_LAYOUT = "drawings/SET_LAYOUT";
const LAYOUT_GRID = "drawings/LAYOUT_GRID";
const LAYOUT_TABLE = "drawings/LAYOUT_TABLE";

export default {
    FETCH_DRAWINGS_SUCCESS,
    FETCH_DRAWINGS_ERROR,
    FETCH_DRAWINGS_IS_LOADING,
    SET_LAYOUT,
    LAYOUT_GRID,
    LAYOUT_TABLE
};