const FETCH_HOMEPAGE_SUCCESS = "home/FETCH_HOMEPAGE_SUCCESS";
const FETCH_HOMEPAGE_ERROR = "home/FETCH_HOMEPAGE_ERROR";
const FETCH_HOMEPAGE_IS_LOADING = "home/FETCH_HOMEPAGE_IS_LOADING";

export default {
    FETCH_HOMEPAGE_ERROR,
    FETCH_HOMEPAGE_SUCCESS,
    FETCH_HOMEPAGE_IS_LOADING
};