const FETCH_NUMBERS_SUCCESS = "numbers/FETCH_NUMBERS_SUCCESS";
const FETCH_NUMBERS_ERROR = "numbers/FETCH_NUMBERS_ERROR";
const FETCH_NUMBERS_IS_LOADING = "numbers/FETCH_NUMBERS_IS_LOADING";
const SET_NUMBERS_SORT_ORDER = "numbers/SET_NUMBERS_SORT_ORDER";
const SET_LAYOUT = "numbers/SET_LAYOUT";
const LAYOUT_GRID = "numbers/AYOUT_GRID";
const LAYOUT_TABLE = "numbers/LAYOUT_TABLE";

export default {
    FETCH_NUMBERS_SUCCESS,
    FETCH_NUMBERS_ERROR,
    FETCH_NUMBERS_IS_LOADING,
    SET_NUMBERS_SORT_ORDER,
    SET_LAYOUT,
    LAYOUT_GRID,
    LAYOUT_TABLE
};